"""empty message

Revision ID: 3f062970d47
Revises: None
Create Date: 2014-11-30 16:46:00.767000

"""

# revision identifiers, used by Alembic.
revision = '3f062970d47'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
