"""empty message

Revision ID: 4cb9869341c0
Revises: 54cfab92f5a1
Create Date: 2015-05-03 17:11:40.438878

"""

# revision identifiers, used by Alembic.
revision = '4cb9869341c0'
down_revision = '54cfab92f5a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_user',
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_user')
    ### end Alembic commands ###
