"""empty message

Revision ID: 54cfab92f5a1
Revises: 968fa5ab793
Create Date: 2015-04-23 02:03:14.208399

"""

# revision identifiers, used by Alembic.
revision = '54cfab92f5a1'
down_revision = '968fa5ab793'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_user',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_user')
    ### end Alembic commands ###
