"""empty message

Revision ID: 968fa5ab793
Revises: 3f062970d47
Create Date: 2015-01-10 03:46:53.100000

"""

# revision identifiers, used by Alembic.
revision = '968fa5ab793'
down_revision = '3f062970d47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.SmallInteger(), nullable=True))
        batch_op.drop_column('role_enum')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_enum', sa.SMALLINT(), nullable=True))
        batch_op.drop_column('role')

    ### end Alembic commands ###
